# Write Kubernetes Deployment Script
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: book-catalog
        image: week08:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "30000"
        - name: DATABASE_URL
          value: "postgresql://task_6_2_user:awmkITMl5hP4GFyuwzEWJcqi25RjVeZ1@dpg-cs4skr08fa8c73ac4bv0-a.oregon-postgres.render.com/task_6_2"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog
spec:
  selector:
    app: book-catalog
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000